name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip mmpk directory
        run: |
          cd /home/runner/work/ha-custom-component-mmpk/ha-custom-component-mmpk/custom_components/mmpk
          zip -r mmpk.zip ./
          mv mmpk.zip ${{ github.workspace }}

      - name: Upload zip to tag (as release asset)
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GH_PAT }}
          file: ${{ github.workspace }}/mmpk.zip
          asset_name: mmpk.zip
          tag: ${{ github.ref_name }}
          overwrite: true
